### PR TITLE
Add response_mode param

### PR DESCRIPTION
**Pull request by Tsutou**
close #51 

Thank you very much for your work.
I would be happy if you could fix this.

### CODE REVIEW

**Comment by m-trieu** [comment]
question how can we pull the data from the id_token, code, and user {} response?

**Comment by Tsutou** [comment]
> question how can we pull the data from the id_token, code, and user {} response?

It seems to be good to use response type of fragment or form_post
https://developer.apple.com/documentation/signinwithapplejs/incorporating_sign_in_with_apple_into_other_platforms

**Comment by ionull** [comment]
Any update on this issue?

**Comment by john-mejia** [comment]
Thanks for merging @jordan-fallon-willowtree !

**Comment by Tsutou** [comment]
Thanks for merging @jordan-fallon-willowtree !

**Pull request merged**
